---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/projects/":
    get:
      summary: Retrieves project
      tags:
      - Project
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Projects found
          content:
            application/json:
              schema:
                type: array
        '404':
          description: Projects not found
          content: {}
  "/api/projects/{id}":
    post:
      summary: Creates a project
      tags:
      - Project
      parameters: []
      responses:
        '201':
          description: Project created
          content: {}
        '400':
          description: Project not created
          content: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
    get:
      summary: Retrieves a project
      tags:
      - Project
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Project found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  user_id:
                    type: integer
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - name
                - user_id
                - created_at
                - updated_at
        '404':
          description: Project not found
          content: {}
    put:
      summary: Updates a project
      tags:
      - Project
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Project updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  user_id:
                    type: integer
                  created_at:
                    type: string
                  updated_at:
                    type: string
                required:
                - id
                - name
                - user_id
                - created_at
                - updated_at
        '404':
          description: Project not found
          content: {}
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
